routes/admin.php
<?php
Route::resource('categories', 'CategoryController');

Route::resource('blogs', 'BlogController');
Route::get('blogs/{id}/active', 'BlogController@active');
Route::get('blogs/{id}/hot', 'BlogController@hot');
Route::post('blogs/upload', 'BlogController@upload')->name('blogs.upload');

Route::resource('products', 'ProductController');
// Route::resource('pages', 'PageController');
Route::get('orders/search', 'ProductController@search')->name('products.search');
Route::resource('orders', 'OrderController');
Route::get('customers/search', 'CustomerController@search')->name('customers.search');
Route::resource('customers', 'CustomerController');

Route::group(['middleware' => ['role:superadmin']], function() {
	Route::resource('permissions', 'PermissionController', ['except' => ['show', 'create']]);
	Route::resource('roles', 'RoleController', ['except' => ['show', 'create']]);
	Route::resource('accounts', 'UserController');
	Route::get('accounts/active/{id}', 'UserController@active')->name('accounts.active');
	Route::get('accounts/reset-password/{id}', 'UserController@resetPasswordDefault')->name('accounts.reset-password');
});

// Route::get('change-password', 'AdminController@getChangePassword')->name('get-change-password');
// Route::post('change-password', 'AdminController@changePassword')->name('change-password');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Role.php
<?php

namespace App;

use Zizaco\Entrust\EntrustRole;

// use OwenIt\Auditing\Auditable;
// use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

class Role extends EntrustRole
{
    // use Auditable;

    /**
     * Audit threshold.
     *
     * @var int
     */
    // protected $auditThreshold = 10;

    protected $fillable = ['name', 'display_name', 'description'];
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Roles\RoleRepository;
use App\Repositories\Permissions\PermissionRepository;
use DB;

class RoleController extends Controller
{
    private $viewPath = 'admin.roles.';
    private $title    = 'Chức vụ';

    protected $role;

    protected $rules = [
		'name' 			=> 'required',
		'display_name'  => 'required'
    ];

    protected $messages = [
		'name.required' 		=> 'Tên chức vụ không được để trống!',
		'display_name.required' => 'Tên chức vụ không được để trống!'
    ];

    function __construct(RoleRepository $role, PermissionRepository $permission)
    {
		$this->role 	  = $role;
		$this->permission = $permission;
    }

    public function index(Request $request)
    {
        $params['except'] = 'superadmin';
    	return view($this->viewPath . 'index')->with([
			'title' 	   => 'Danh sách ' . $this->title,
			'roles'  	   => $this->role->getByParam($params, 10),
			'permissions'  => $this->permission->getAllWithSort()
    	]);
    }

    public function store(Request $request)
    {
    	DB::beginTransaction();
		try {
			$this->validate($request, $this->rules, $this->messages);
			$role = $this->role->store($request->all());
			DB::commit();
			notify()->flash('Thêm mới ' . $this->title . ' thành công', 'success', [
			    'timer' => 1500]);
			return redirect()->route('roles.index');
		}
		catch(Exception $e) {
			DB::rollback();
    	    notify()->flash('Có lỗi xảy ra', 'warning', [
    	        'timer' => 1500]);
    	    return redirect()->back()->withErrors($exception->validator->errors())->withInput();
    	}
    }

    public function edit($id)
    {
        $role = $this->role->getById($id);

        if (is_null($role) || ($role->name == 'superadmin')) {
            notify()->flash('Không tìm thấy trang yêu cầu', 'warning', [
                'timer' => 1500]);
            return redirect()->back();
        }

        return view($this->viewPath . 'index')->with([
            'title'    		=> 'Cập nhật ' . $this->title,
            'roles'     	=> $this->role->getByParam([], 10),
            'permissions'  => $this->permission->getAllWithSort(),
            'role_edit'		=> $role
        ]);
    }

    public function update($id, Request $request)
    {
        $role = $this->role->getById($id);

        if (is_null($role) || ($role->name == 'superadmin')) {
            notify()->flash('Không tìm thấy trang yêu cầu', 'warning', [
                'timer' => 1500]);
            return redirect()->back();
        }
        DB::beginTransaction();
        try {
            $this->validate($request, $this->rules, $this->messages);
            if ($this->role->update($role, $request->all())) {
            	DB::commit();
                notify()->flash('Cập nhật ' . $this->title . ' thành công', 'success', [
                    'timer' => 1500]);
                return redirect()->route('roles.index');
            }else {
                notify()->flash('Cập nhât ' . $this->title . ' thất bại', 'error', [
                    'timer' => 1500]);
                return redirect()->back();
            }
        } catch(\Illuminate\Validation\ValidationException $exception) {
        	DB::rollback();
            notify()->flash('Vui lòng kiểm tra lại các thông tin cần nhập', 'warning', [
                'timer' => 1500]);
            return redirect()->back()->withErrors($exception->validator->errors())->withInput();
        }
    }

    public function destroy($id)
    {
        $role = $this->role->getById($id);

        if (is_null($role) || ($role->name == 'superadmin')) {
            notify()->flash('Không tìm thấy trang yêu cầu', 'warning', [
                'timer' => 1500]);
            return redirect()->back();
        }

        try {
            if ($this->role->delete($role)) {
                notify()->flash('Xóa ' . $this->title . ' thành công', 'success', [
                    'timer' => 1500]);
                return [
                    'code'   => 1,
                    'messages' => 'Xóa tài khoản thành công'
                ];
            }else {
                notify()->flash('Xóa ' . $this->title . ' thất bại', 'error', [
                    'timer' => 1500]);
                return [
                    'code'   => 0
                ];
            }
        } catch(\Illuminate\Validation\ValidationException $exception) {
            notify()->flash('Có lỗi trong quá trình xóa dữ liệu', 'warning', [
                'timer' => 1500]);
            return redirect()->back()->withErrors($exception->validator->errors())->withInput();
        }
    }
}

app/Http/Controllers/Api/V1/RoleController.php
<?php

namespace App\Http\Controllers\Api\V1;

use Illuminate\Http\Request;
use App\Http\Controllers\Api\RestfulHandler;
use App\Http\Controllers\Api\TransformerTrait;
use App\Http\Controllers\Api\ApiController;

use App\Repositories\Roles\RoleRepository;
use App\Http\Transformers\RoleTransformer;

class RoleController extends ApiController
{
    use TransformerTrait, RestfulHandler;

    protected $role;

    protected $validationRules = [
        'name'          => 'required|unique:roles,name,',
        'display_name'  => 'required',
        'users'         => 'array',
        'users.*'       => 'required|exists:users,uuid',
        'permissions'   => 'array',
        'permissions.*' => 'required|exists:permissions,id',
    ];

    protected $validationMessages = [
        'name.required'          => 'Vui lòng nhập tên',
        'name.unique'            => 'Tên đã tồn tại, vui lòng nhập tên khác',
        'users.array'           => 'Admin không đúng định dạng',
        'users.*.required'      => 'Vui lòng chọn users',
        'users.*.exists'        => 'Không tồn tại users này',
        'permissions.array'      => 'Permission không đúng định dạng',
        'permissions.*.required' => 'Vui lòng chọn permission',
        'permissions.*.exists'   => 'Không tồn tại permission này',
    ];

    public function __construct(RoleRepository $role, RoleTransformer $transformer)
    {
        $this->role = $role;
        $this->setTransformer($transformer);
        $this->checkPermission('role');
    }

    public function getResource()
    {
        return $this->role;
    }

    public function index(Request $request) {
        $pageSize = $request->get('limit', 25);
        $sort = $request->get('sort', 'created_at:-1');

        $models = $this->getResource()->getByParam($request->all(), $pageSize, explode(':', $sort));
        return $this->successResponse($models);
    }

    public function update(Request $request, $id) {
        if (!$data = $this->getResource()->getById($id)) {
            return $this->notFoundResponse();
        }

        \DB::beginTransaction();

        try {
            $this->validationRules['name'] .= $id . ',id';
            $this->validate($request, $this->validationRules, $this->validationMessages);

            $params = $request->all();
            $model = $this->getResource()->update($id, $params);

            \DB::commit();
            return $this->successResponse($model);
        }
        catch (\Illuminate\Validation\ValidationException $validationException) {
            \DB::rollback();
            return $this->errorResponse([
                'errors' => $validationException->validator->errors(),
                'exception' => $validationException->getMessage()
            ]);
        }
        catch (\Exception $e) {
            \DB::rollback();
            throw $e;
        }
    }

}

resources/views/admin/roles/index.blade.php
@extends('adminlte::page')

@section('title', $title)

@section('content_header')

@stop

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-info alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4>Hướng dẫn</h4>
                Mỗi chức vụ sẽ có tên và nhóm quyền hạn khác nhau.
            </div>
        </div>
        <div class="col-md-5 col-sm-12 col-xs-12">
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title">Danh sách chức vụ</h3>
                </div>

                <div class="box-body">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th width="15">#</th>
                                <th width="150" class="text-center">Mã</th>
                                <th width="150" class="text-center">Tên</th>
                                <th class="text-center">Thao tác</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($roles as $key => $role)
                                <tr>
                                    <td class="text-center">{{ ++$key }}</td>
                                    <td class="text-center">{{ $role->name }}</td>
                                    <td class="text-center">{{ $role->display_name }}</td>
                                    <td class="text-center">
                                        <a href="{{ route('roles.edit', $role->id) }}" class="btn btn-xs" data-toggle="tooltip" title="Sửa">
                                            <i class="fa fa-pencil" aria-hidden="true"></i>
                                        </a>
                                        <a data-href="{{ route('roles.destroy', $role->id) }}" class="btn btn-xs delete-btn" data-toggle="tooltip" title="Xóa">
                                            <i class="fa fa-times" aria-hidden="true"></i>
                                        </a>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="4" class="text-center">Không có dữ liệu !</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
                <div class="box-footer">
                    @if (count($roles))
                        {!! $roles->appends([Request::all()])->links() !!}
                    @endif
                </div>
            </div>
        </div>

        <div class="col-md-7 col-sm-12 col-xs-12">
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ isset($role_edit) ? 'Cập nhật' : 'Thêm mới' }} chức vụ</h3>
                </div>
                <div class="box-body">
                    <form action="{{ isset($role_edit) ? route('roles.update', $role_edit->id) : route('roles.store')}}" method="POST" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        @if (isset($role_edit))
                            <input name="_method" type="hidden" value="PUT">
                        @endif
                        <div class="form-group {{ $errors->first('name') ? 'has-error' : ''}}">
                            <label class="control-label" for="title">Mã chức vụ <b style="color: red">*</b></label>
                            <input type="text" class="form-control" name="name" id="name" placeholder="Viết liền không dấu. VD: nhanvienkinhdoanh" value="{{ old('title', isset($role_edit) ? $role_edit->name : '')  }}">
                            <span class="help-block">{{ $errors->first('name') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('display_name') ? 'has-error' : ''}}">
                            <label class="control-label" for="title">Tên chức vụ <b style="color: red">*</b></label>
                            <input type="text" class="form-control" name="display_name" id="display_name" placeholder="Nhập tên chức vụ" value="{{ old('title', isset($role_edit) ? $role_edit->display_name : '')  }}">
                            <span class="help-block">{{ $errors->first('display_name') }}</span>
                        </div>
                        <div class="form-group {{ $errors->first('permissions') ? 'has-error' : ''}}">
                            <label class="col-md-12 row">Quyền hạn <b style="color: red">*</b></label>
                            
                            @forelse ($permissions as $key => $perms)
                                <div class="col-md-12">
                                    <label><i class="fa fa-ellipsis-v"></i> {{ ucwords($key) }}</label>
                                </div>
                                @foreach($perms as $perm)
                                <div class="col-md-4 checkbox" style="margin-top: 10px;">
                                    <label>
                                        <input type="checkbox" name="permissions[]" id="permissions" value="{{ $perm->id }}" {{ (isset($role_edit) && in_array($perm->id, array_pluck($role_edit->perms()->get()->all(), 'id'))) ? 'checked' : '' }}>
                                        {{ $perm->display_name }}
                                    </label>
                                </div>
                                @endforeach
                            @empty
                            <p>Chưa có quyền hạn nào</p>
                            @endforelse
                            <span class="col-md-12 help-block">{{ $errors->first('permissions') }}</span>
                        </div>

                        <div class="form-group col-md-12 row" style="margin-top: 20px;">
                            <button type="submit" class="btn btn-{{ isset($role_edit) ? 'warning' : 'success' }} btn-sm">{{ isset($role_edit) ? 'Cập nhật' : 'Thêm mới' }}</button>
                            @if (isset($role_edit))
                                <a href="{{ route('roles.index') }}" class="btn btn-default btn-sm btn-cancel">Hủy</a>
                            @endif
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
@stop

@section('js')
    <script type="text/javascript">
        $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
          checkboxClass: 'icheckbox_flat-green'
        });
    </script>
@stop