routes/admin.php
<?php
Route::resource('categories', 'CategoryController');

Route::resource('blogs', 'BlogController');
Route::get('blogs/{id}/active', 'BlogController@active');
Route::get('blogs/{id}/hot', 'BlogController@hot');
Route::post('blogs/upload', 'BlogController@upload')->name('blogs.upload');

Route::resource('products', 'ProductController');
// Route::resource('pages', 'PageController');
Route::get('orders/search', 'ProductController@search')->name('products.search');
Route::resource('orders', 'OrderController');
Route::get('customers/search', 'CustomerController@search')->name('customers.search');
Route::resource('customers', 'CustomerController');

Route::group(['middleware' => ['role:superadmin']], function() {
	Route::resource('permissions', 'PermissionController', ['except' => ['show', 'create']]);
	Route::resource('roles', 'RoleController', ['except' => ['show', 'create']]);
	Route::resource('accounts', 'UserController');
	Route::get('accounts/active/{id}', 'UserController@active')->name('accounts.active');
	Route::get('accounts/reset-password/{id}', 'UserController@resetPasswordDefault')->name('accounts.reset-password');
});

// Route::get('change-password', 'AdminController@getChangePassword')->name('get-change-password');
// Route::post('change-password', 'AdminController@changePassword')->name('change-password');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/CustomerController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Admin\AdminController;
use App\Repositories\Customers\CustomerRepository;

class CustomerController extends AdminController
{
    private $viewPath = 'admin.customers.';
    private $title    = 'Khách hàng';

    protected $customer;

    protected $rules = [
        'name'       => 'required',
        'phone'      => 'required',
        'address' 	 => 'required'
    ];

    protected $messages = [
        'name.required'       => 'Tên không được để trống!',
        'phone.required'      => 'Số điện thoại không được để trống!',
        'address.required'	 => 'Địa chỉ không được để trống!'
    ];

    function __construct(CustomerRepository $customer)
    {
        $this->customer = $customer;
        $this->checkPermission('customer');
    }

    public function index(Request $request)
    {
        return view($this->viewPath . 'index')->with([
            'title' => 'Danh sách ' . $this->title,
            'customers' => $this->customer->getByParam([], 10)
        ]);
    }

    public function search(Request $request)
    {
        return response()->json($this->customer->getByParam($request->all(), 10));
    }

    public function create()
    {
        return view($this->viewPath . 'create')->with([
            'title' => 'Tạo mới khách hàng ' . $this->title
        ]);
    }

    public function store(Request $request)
    {
        try {
            $this->validate($request, $this->rules, $this->messages);
            if ($this->customer->store($request->all())) {
                notify()->flash('Thêm mới ' . $this->title . ' thành công', 'success', [
                    'timer' => 1500]);
                return redirect()->route('customers.index');
            }else {
                notify()->flash('Thêm mới ' . $this->title . ' thất bại', 'error', [
                    'timer' => 1500]);
                return redirect()->back();
            }
        } catch(\Illuminate\Validation\ValidationException $exception) {
            notify()->flash('Vui lòng kiểm tra lại các thông tin cần nhập', 'warning', [
                'timer' => 1500]);
            return redirect()->back()->withErrors($exception->validator->errors())->withInput();
        }
    }

    public function edit($id)
    {
        $customer = $this->customer->getById($id);

        if (is_null($customer)) {
            notify()->flash('Không tìm thấy trang yêu cầu', 'warning', [
                'timer' => 1500]);
            return redirect()->back();
        }

        return view($this->viewPath . 'edit')->with([
            'title'      => 'Cập nhật ' . $this->title,
            'customer'       => $customer
        ]);
    }

    public function update($id, Request $request)
    {
        try {
            $this->validate($request, $this->rules, $this->messages);

            $customer = $this->customer->getById($id);

            if (is_null($customer)) {
                notify()->flash('Không tìm thấy trang yêu cầu', 'warning', [
                    'timer' => 1500]);
                return redirect()->back();
            }

            if ($this->customer->update($customer, $request->all())) {
                notify()->flash('Cập nhật ' . $this->title . ' thành công', 'success', [
                    'timer' => 1500]);
                return redirect()->route('customers.index');
            }else {
                notify()->flash('Cập nhật ' . $this->title . ' thất bại', 'error', [
                    'timer' => 1500]);
                return redirect()->back();
            }
        } catch(\Illuminate\Validation\ValidationException $exception) {
            notify()->flash('Vui lòng kiểm tra lại các thông tin cần nhập', 'warning', [
                'timer' => 1500]);
            return redirect()->back()->withErrors($exception->validator->errors())->withInput();
        }
    }

    public function destroy($id)
    {
        try {
            $customer = $this->customer->getById($id);

            if (is_null($customer)) {
                notify()->flash('Không tìm thấy trang yêu cầu', 'warning', [
                    'timer' => 1500]);
                return redirect()->back();
            }

            if ($this->customer->delete($customer)) {
                notify()->flash('Xóa ' . $this->title . ' thành công', 'success', [
                    'timer' => 1500]);
                return response()->json([
                    'code'    => 1,
                    'message' => 'Xóa thành công'
                ]);
            }else {
                notify()->flash('Xóa ' . $this->title . ' thất bại', 'error', [
                    'timer' => 1500]);
                return response()->json([
                    'code'    => 0,
                    'message' => 'Xóa thất bại'
                ]);
            }
        } catch(\Illuminate\Validation\ValidationException $exception) {
            notify()->flash('Có lỗi trong quá trình xóa dữ liệu', 'warning', [
                'timer' => 1500]);
            return redirect()->back()->withErrors($exception->validator->errors())->withInput();
        }
    }
}

app/Http/Controllers/Api/V1/CustomerController.php
<?php

namespace App\Http\Controllers\Api\V1;

use Illuminate\Http\Request;
use App\Http\Controllers\Api\ApiController;
use App\Http\Controllers\Api\RestfulHandler;
use App\Http\Controllers\Api\TransformerTrait;
use App\Repositories\Customers\CustomerRepository;
use App\Http\Transformers\CustomerTransformer;

class CustomerController extends ApiController
{
	use TransformerTrait, RestfulHandler;

    protected $customer;

    protected $rules = [
        'name'       => 'required'
    ];

    protected $messages = [
        'name.required'       => 'Tên không được để trống!'
    ];

    function __construct(CustomerRepository $customer, CustomerTransformer $transformer)
    {
        $this->customer = $customer;
        $this->setTransformer($transformer);
        $this->checkPermission('customer');
    }

    public function getResource()
    {
        return $this->customer;
    }

    public function index(Request $request)
    {
        $pageSize = $request->get('limit', 25);
        $sort = explode(':', $request->get('sort', 'id:1'));

        $models = $this->getResource()->getByQuery($request->all(), $pageSize, $sort);
        return $this->successResponse($models);
    }

    public function store(Request $request)
    {
        try {
            $this->validate($request, $this->rules, $this->messages);
            $data = $this->getResource()->store($request->all());
            return $this->successResponse($data);
        } catch(\Illuminate\Validation\ValidationException $validationException) {
            return $this->errorResponse([
                'errors' => $validationException->validator->errors(),
                'exception' => $validationException->getMessage()
            ]);
        } catch (\Exception $e) {
            DB::rollback();
            throw $e;
        }
    }

    public function update($id, Request $request)
    {
        try {
            $this->validate($request, $this->rules, $this->messages);

            $customer = $this->customer->getById($id);

            if (is_null($customer)) {
                return $this->notFoundResponse();
            }

            $data = $this->getResource()->update($customer, $request->all());
            return $this->successResponse($data);
        } catch (\Illuminate\Validation\ValidationException $validationException) {
            return $this->errorResponse([
                'errors' => $validationException->validator->errors(),
                'exception' => $validationException->getMessage()
            ]);
        } catch (\Exception $e) {
            throw $e;
        }
    }
}

resources/views/admin/customers/create.blade.php
@extends('adminlte::page')

@section('title', $title)

@section('css')
@stop

@section('content')
    <div class="row">
        <div class="col-md-12 admin-blog-create">
            <div class="box box-success">
                <form action="{{ route('customers.store') }}" method="POST" enctype="multipart/form-data">
                    <div class="box-header with-border">
                        <h3 class="box-title">Thêm mới khách hàng</h3>
                        <span class="pull-right">
                            <button type="submit" class="btn btn-success"><i class="fa fa-floppy-o" aria-hidden="true"></i> Thêm mới</button>
                            <a href="{{ route('customers.index') }}" class="btn btn-default"><i class="fa fa-long-arrow-left"></i> Trở lại</a>
                        </span>
                    </div>
                    {{ csrf_field() }}
                    <div class="box-body">
                        <div class="col-md-12">
                            <div class="form-group {{ $errors->first('name') ? 'has-error' : '' }}">
                                <label for="">Họ tên khách hàng <b style="color: red">*</b></label>
                                <input type="text" class="form-control" name="name" placeholder="Tiêu đề" value="{{ old('name') }}">
                                <span class="help-block">{{ $errors->first('name') }}</span>
                            </div>
                            <div class="form-group {{ $errors->first('phone') ? 'has-error' : '' }}">
                                <label for="">Số điện thoại <b style="color: red">*</b></label>
                                <input type="text" class="form-control" name="phone" placeholder="Tiêu đề" value="{{ old('phone') }}">
                                <span class="help-block">{{ $errors->first('phone') }}</span>
                            </div>
                            <div class="form-group {{ $errors->first('address') ? 'has-error' : '' }}">
                                <label for="">Địa chỉ <b style="color: red">*</b></label>
                                <input type="text" class="form-control" name="address" placeholder="Tiêu đề" value="{{ old('address') }}">
                                <span class="help-block">{{ $errors->first('address') }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-success"><i class="fa fa-floppy-o" aria-hidden="true"></i> Thêm mới</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@stop

@section('js')</script>
    <script type="text/javascript">
    </script>
@stop

resources/views/admin/customers/edit.blade.php
@extends('adminlte::page')

@section('title', $title)

@section('css')
    <style type="text/css">
    </style>
@stop

@section('content')
    <div class="row">
        <div class="col-md-12 admin-blog-create">
            <div class="box box-success">
                <form action="{{ route('customers.update', $customer->id) }}" method="POST" enctype="multipart/form-data">
                    <div class="box-header with-border">
                        <h3 class="box-title">Sửa thông tin khách hàng</h3>
                        <span class="pull-right">
                            <button type="submit" class="btn btn-warning"><i class="fa fa-floppy-o" aria-hidden="true"></i> Cập nhật</button>
                            <a href="{{ route('customers.index') }}" class="btn btn-default"><i class="fa fa-long-arrow-left"></i> Trờ lại</a>
                        </span>
                    </div>
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    <div class="box-body">
                        <div class="col-md-12">
                            <div class="form-group {{ $errors->first('name') ? 'has-error' : '' }}">
                                <label for="">Họ tên khách hàng <b style="color: red">*</b></label>
                                <input type="text" class="form-control" name="name" placeholder="Tiêu đề" value="{{ Request::old('name', $customer->name) }}">
                                <span class="help-block">{{ $errors->first('name') }}</span>
                            </div>
                            <div class="form-group {{ $errors->first('phone') ? 'has-error' : '' }}">
                                <label for="">Số điện thoại <b style="color: red">*</b></label>
                                <input type="text" class="form-control" name="phone" placeholder="Tiêu đề" value="{{ Request::old('phone', $customer->phone) }}">
                                <span class="help-block">{{ $errors->first('phone') }}</span>
                            </div>
                            <div class="form-group {{ $errors->first('address') ? 'has-error' : '' }}">
                                <label for="">Địa chỉ <b style="color: red">*</b></label>
                                <input type="text" class="form-control" name="address" placeholder="Tiêu đề" value="{{ Request::old('address', $customer->address) }}">
                                <span class="help-block">{{ $errors->first('address') }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-warning"><i class="fa fa-floppy-o" aria-hidden="true"></i> Cập nhật</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script type="text/javascript">
    </script>
@stop

resources/views/admin/customers/index.blade.php
@extends('adminlte::page')

@section('title', $title)

@section('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/admin.css') }}">
@stop

@section('content')
    <div class="row">
        <div class="col-md-12" id="backend-blog">
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title">Danh sách khách hàng</h3>
                    <span class="pull-right">
                        <a href="{{ route('customers.create') }}" class="btn btn-success"><i class="fa fa-plus"></i> Thêm mới</a>
                    </span>
                </div>

                <table class="table table-striped table-hover table-bordered">
                    <thead>
                        <tr>
                            <th width="35">#</th>
                            <th width="200">Tên</th>
                            <th width="200">Só điện thoại</th>
                            <th>Địa chỉ</th>
                            <th width="100" class="text-center">Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($customers as $key => $customer)
                            <tr>
                                <td class="text-center">{{ ++$key }}</td>
                                <td>{{ $customer->name }}</td>
                                <td>{{ $customer->phone }}</td>
                                <td>{{ $customer->address }}</td>
                                <td class="text-center">
                                    <a href="{{ route('customers.edit', $customer->id) }}" class="btn btn-xs" data-toggle="tooltip" title="Sửa">
                                        <i class="fa fa-pencil" aria-hidden="true"></i>
                                    </a>
                                    <a href="#" data-href="{{ route('customers.destroy', $customer->id) }}" class="btn btn-xs btn-destroy label-cancel" data-toggle="tooltip" title="Xóa">
                                        <i class="fa fa-times" aria-hidden="true"></i>
                                    </a>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="5" class="text-center">Không có dữ liệu !</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
                <div class="box-footer">
                    <div class="pull-right">
                        @if (count($customers))
                            {!! $customers->appends([Request::all()])->links() !!}
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@section('js')
<script type="text/javascript">
</script>
@stop