routes/admin.php
<?php
Route::resource('categories', 'CategoryController');

Route::resource('blogs', 'BlogController');
Route::get('blogs/{id}/active', 'BlogController@active');
Route::get('blogs/{id}/hot', 'BlogController@hot');
Route::post('blogs/upload', 'BlogController@upload')->name('blogs.upload');

Route::resource('products', 'ProductController');
// Route::resource('pages', 'PageController');
Route::get('orders/search', 'ProductController@search')->name('products.search');
Route::resource('orders', 'OrderController');
Route::get('customers/search', 'CustomerController@search')->name('customers.search');
Route::resource('customers', 'CustomerController');

Route::group(['middleware' => ['role:superadmin']], function() {
	Route::resource('permissions', 'PermissionController', ['except' => ['show', 'create']]);
	Route::resource('roles', 'RoleController', ['except' => ['show', 'create']]);
	Route::resource('accounts', 'UserController');
	Route::get('accounts/active/{id}', 'UserController@active')->name('accounts.active');
	Route::get('accounts/reset-password/{id}', 'UserController@resetPasswordDefault')->name('accounts.reset-password');
});

// Route::get('change-password', 'AdminController@getChangePassword')->name('get-change-password');
// Route::post('change-password', 'AdminController@changePassword')->name('change-password');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Admin\AdminController;
use App\Repositories\Products\ProductRepository;
use App\Repositories\Products\Product;

class ProductController extends AdminController
{
    private $viewPath = 'admin.products.';
    private $title    = 'Sản phẩm';

    protected $product;

    protected $rules = [
        'name'       => 'required',
        'default_price'      => 'required|numeric',
        'price_per_page' 	 => 'required|numeric'
    ];

    protected $messages = [
        'name.required'       		=> 'Tên không được để trống!',
        'default_price.required'	=> 'Giá không được để trống!',
        'default_price.numeric'		=> 'Giá phải ở dạng số',
        'price_per_page.required'	=> 'Giá mỗi trang không được để trống!',
        'price_per_page.numeric'	=> 'Giá mỗi trang phải ở dạng số'
    ];

    function __construct(ProductRepository $product, Product $model)
    {
        $this->product = $product;
        $this->model   = $model;
    }

    public function index(Request $request)
    {
        return view($this->viewPath . 'index')->with([
            'title' => 'Danh sách ' . $this->title,
            'products' => $this->product->getByParam([], 10)
        ]);
    }

    public function create()
    {
        $types = $this->model->getTypes();
        return view($this->viewPath . 'create')->with([
            'title' => 'Tạo mới khách hàng ' . $this->title,
            'types'    => $types
        ]);
    }

    public function store(Request $request)
    {
        try {
            $this->validate($request, $this->rules, $this->messages);
            if ($this->product->store($request->all())) {
                notify()->flash('Thêm mới ' . $this->title . ' thành công', 'success', [
                    'timer' => 1500]);
                return redirect()->route('products.index');
            }else {
                notify()->flash('Thêm mới ' . $this->title . ' thất bại', 'error', [
                    'timer' => 1500]);
                return redirect()->back();
            }
        } catch(\Illuminate\Validation\ValidationException $exception) {
            notify()->flash('Vui lòng kiểm tra lại các thông tin cần nhập', 'warning', [
                'timer' => 1500]);
            return redirect()->back()->withErrors($exception->validator->errors())->withInput();
        }
    }

    public function edit($id)
    {
        $product = $this->product->getById($id);
        $types = $this->model->getTypes();
        if (is_null($product)) {
            notify()->flash('Không tìm thấy trang yêu cầu', 'warning', [
                'timer' => 1500]);
            return redirect()->back();
        }

        return view($this->viewPath . 'edit')->with([
            'title'     => 'Cập nhật ' . $this->title,
            'product'   => $product,
            'types'     => $types
        ]);
    }

    public function update($id, Request $request)
    {
        try {
            $this->validate($request, $this->rules, $this->messages);

            $product = $this->product->getById($id);

            if (is_null($product)) {
                notify()->flash('Không tìm thấy trang yêu cầu', 'warning', [
                    'timer' => 1500]);
                return redirect()->back();
            }

            if ($this->product->update($product, $request->all())) {
                notify()->flash('Cập nhật ' . $this->title . ' thành công', 'success', [
                    'timer' => 1500]);
                return redirect()->route('products.index');
            }else {
                notify()->flash('Cập nhật ' . $this->title . ' thất bại', 'error', [
                    'timer' => 1500]);
                return redirect()->back();
            }
        } catch(\Illuminate\Validation\ValidationException $exception) {
            notify()->flash('Vui lòng kiểm tra lại các thông tin cần nhập', 'warning', [
                'timer' => 1500]);
            return redirect()->back()->withErrors($exception->validator->errors())->withInput();
        }
    }

    public function destroy($id)
    {
        try {
            $product = $this->product->getById($id);

            if (is_null($product)) {
                notify()->flash('Không tìm thấy trang yêu cầu', 'warning', [
                    'timer' => 1500]);
                return redirect()->back();
            }

            if ($this->product->delete($product)) {
                notify()->flash('Xóa ' . $this->title . ' thành công', 'success', [
                    'timer' => 1500]);
                return response()->json([
                    'code'    => 1,
                    'message' => 'Xóa thành công'
                ]);
            }else {
                notify()->flash('Xóa ' . $this->title . ' thất bại', 'error', [
                    'timer' => 1500]);
                return response()->json([
                    'code'    => 0,
                    'message' => 'Xóa thất bại'
                ]);
            }
        } catch(\Illuminate\Validation\ValidationException $exception) {
            notify()->flash('Có lỗi trong quá trình xóa dữ liệu', 'warning', [
                'timer' => 1500]);
            return redirect()->back()->withErrors($exception->validator->errors())->withInput();
        }
    }

    public function search(Request $request)
    {
        return response()->json($this->product->getByParam($request->all(), 10));
    }
}

app/Http/Controllers/Api/V1/ProductController.php
<?php

namespace App\Http\Controllers\Api\V1;

use Illuminate\Http\Request;
use App\Http\Controllers\Api\ApiController;
use App\Http\Controllers\Api\RestfulHandler;
use App\Http\Controllers\Api\TransformerTrait;
use App\Repositories\Products\ProductRepository;
use App\Repositories\Products\Product;
use App\Http\Transformers\ProductTransformer;

class ProductController extends ApiController
{
    use TransformerTrait, RestfulHandler;

    protected $product;

    protected $rules = [
        'name'       => 'required',
        'default_price'      => 'numeric'
    ];

    protected $messages = [
        'name.required'       		=> 'Tên không được để trống!',
        'default_price.numeric'		=> 'Giá phải ở dạng số'
    ];

    function __construct(ProductRepository $product, Product $model, ProductTransformer $transformer)
    {
        $this->product = $product;
        $this->model   = $model;
        $this->setTransformer($transformer);
        $this->checkPermission('product');
    }

    public function getResource()
    {
        return $this->product;
    }

    public function index(Request $request)
    {
        $pageSize = $request->get('limit', 25);
        $sort = explode(':', $request->get('sort', 'id:1'));
        $params = $request->all();
        
        return $this->successResponse($this->getResource()->getByQuery($params, $pageSize, $sort));
    }

    public function store(Request $request)
    {
        try {
            $this->validate($request, $this->rules, $this->messages);
            $data = $this->getResource()->store($request->all());
            return $this->successResponse($data);
        } catch(\Illuminate\Validation\ValidationException $validationException) {
            return $this->errorResponse([
                'errors' => $validationException->validator->errors(),
                'exception' => $validationException->getMessage()
            ]);
        } catch (\Exception $e) {
            throw $e;
        }
    }

    public function update($id, Request $request)
    {
        try {
            $this->validate($request, $this->rules, $this->messages);

            $product = $this->product->getById($id);

            if (is_null($product)) {
                return $this->notFoundResponse();
            }
            $data = $this->getResource()->update($product, $request->all());
            return $this->successResponse($data);

        } catch(\Illuminate\Validation\ValidationException $validationException) {
            return $this->errorResponse([
                'errors' => $validationException->validator->errors(),
                'exception' => $validationException->getMessage()
            ]);
        } catch (\Exception $e) {
            throw $e;
        }
    }
}

resources/views/admin/products/create.blade.php
@extends('adminlte::page')

@section('title', $title)

@section('css')
@stop

@section('content')
    <div class="row">
        <div class="col-md-12 admin-blog-create">
            <div class="box box-success">
                <form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">
                    <div class="box-header with-border">
                        <h3 class="box-title">Thêm mới sản phẩm</h3>
                        <span class="pull-right">
                            <button type="submit" class="btn btn-success"><i class="fa fa-floppy-o" aria-hidden="true"></i> Thêm mới</button>
                            <a href="{{ route('products.index') }}" class="btn btn-default"><i class="fa fa-long-arrow-left"></i> Trở lại</a>
                        </span>
                    </div>
                    {{ csrf_field() }}
                    <div class="box-body">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Loại sản phẩm</label>
                                <select class="form-control" name="type">
                                    @foreach ($types as $key => $type)
                                    <option value="{{ $key }}">{{ $type }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group {{ $errors->first('name') ? 'has-error' : '' }}">
                                <label for="">Tên sản phẩm <b style="color: red">*</b></label>
                                <input type="text" class="form-control" name="name" placeholder="Nhập tên sản phẩm" value="{{ old('name') }}">
                                <span class="help-block">{{ $errors->first('name') }}</span>
                            </div>
                            <div class="form-group {{ $errors->first('description') ? 'has-error' : '' }}">
                                <label for="">Mô tả</label>
                                <textarea class="form-control" name="description" rows="4" placeholder="Nhập mô tả">{{ old('description') }}</textarea>
                                <span class="help-block">{{ $errors->first('description') }}</span>
                            </div>
                            <div class="form-group {{ $errors->first('default_price') ? 'has-error' : '' }}">
                                <label for="">Giá <b style="color: red">*</b></label>
                                <input type="number" class="form-control" name="default_price" placeholder="Nhập giá" value="{{ old('default_price') }}">
                                <span class="help-block">{{ $errors->first('default_price') }}</span>
                            </div>
                            <div class="form-group {{ $errors->first('price_per_page') ? 'has-error' : '' }}">
                                <label for="">Giá mỗi trang<b style="color: red">*</b></label>
                                <input type="number" class="form-control" name="price_per_page" placeholder="Nhập giá mỗi trang" value="{{ old('price_per_page') }}">
                                <span class="help-block">{{ $errors->first('price_per_page') }}</span>
                            </div>
                            <div class="form-group {{ $errors->first('size') ? 'has-error' : '' }}">
                                <label for="">Kích thước<b style="color: red">*</b></label>
                                <input type="number" class="form-control" name="size" placeholder="Nhập kích thước" value="{{ old('size') }}">
                                <span class="help-block">{{ $errors->first('size') }}</span>
                            </div>
                            <div class="form-group {{ $errors->first('quantity') ? 'has-error' : '' }}">
                                <label for="">Số lượng<b style="color: red">*</b></label>
                                <input type="number" class="form-control" name="quantity" placeholder="Số lượng (hoặc số trang)" value="{{ old('quantity') }}">
                                <span class="help-block">{{ $errors->first('quantity') }}</span>
                            </div>
                            <div class="form-group {{ $errors->first('kpi') ? 'has-error' : '' }}">
                                <label for="">Chiết khấu</label>
                                <input type="text" class="form-control" name="kpi" placeholder="VD: 0.3 ~ 30%" value="{{ old('kpi') }}">
                                <span class="help-block">{{ $errors->first('kpi') }}</span>
                            </div>
                            <div class="form-group {{ $errors->first('time_avg') ? 'has-error' : '' }}">
                                <label for="">Thời gian làm ước tính</label>
                                <input type="text" class="form-control" name="time_avg" placeholder="Đơn vị phút" value="{{ old('time_avg') }}">
                                <span class="help-block">{{ $errors->first('time_avg') }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-success"><i class="fa fa-floppy-o" aria-hidden="true"></i> Thêm mới</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@stop

@section('js')</script>
    <script type="text/javascript">
    </script>
@stop

resources/views/admin/products/edit.blade.php
@extends('adminlte::page')

@section('title', $title)

@section('css')
    <style type="text/css">
    </style>
@stop

@section('content')
    <div class="row">
        <div class="col-md-12 admin-blog-create">
            <div class="box box-success">
                <form action="{{ route('products.update', $product->id) }}" method="POST" enctype="multipart/form-data">
                    <div class="box-header with-border">
                        <h3 class="box-title">Sửa thông tin sản phẩm</h3>
                        <span class="pull-right">
                            <button type="submit" class="btn btn-warning"><i class="fa fa-floppy-o" aria-hidden="true"></i> Cập nhật</button>
                            <a href="{{ route('products.index') }}" class="btn btn-default"><i class="fa fa-long-arrow-left"></i> Trờ lại</a>
                        </span>
                    </div>
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    <div class="box-body">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Loại sản phẩm</label>
                                <select class="form-control">
                                    @foreach ($types as $key => $type)
                                    <option value="{{ $key }}" {{ $product->type == $key ? 'selected' : '' }}>{{ $type }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group {{ $errors->first('name') ? 'has-error' : '' }}">
                                <label for="">Tên sản phẩm <b style="color: red">*</b></label>
                                <input type="text" class="form-control" name="name" placeholder="Nhập tên sản phẩm" value="{{ old('name', $product->name) }}">
                                <span class="help-block">{{ $errors->first('name') }}</span>
                            </div>
                            <div class="form-group {{ $errors->first('description') ? 'has-error' : '' }}">
                                <label for="">Mô tả</label>
                                <textarea class="form-control" name="description" rows="4" placeholder="Nhập mô tả">{{ old('description', $product->description) }}</textarea>
                                <span class="help-block">{{ $errors->first('description') }}</span>
                            </div>
                            <div class="form-group {{ $errors->first('default_price') ? 'has-error' : '' }}">
                                <label for="">Giá <b style="color: red">*</b></label>
                                <input type="number" class="form-control" name="default_price" placeholder="Nhập giá" value="{{ old('default_price', $product->default_price) }}">
                                <span class="help-block">{{ $errors->first('default_price') }}</span>
                            </div>
                            <div class="form-group {{ $errors->first('price_per_page') ? 'has-error' : '' }}">
                                <label for="">Giá mỗi trang<b style="color: red">*</b></label>
                                <input type="number" class="form-control" name="price_per_page" placeholder="Nhập giá mỗi trang" value="{{ old('price_per_page', $product->price_per_page) }}">
                                <span class="help-block">{{ $errors->first('price_per_page') }}</span>
                            </div>
                            <div class="form-group {{ $errors->first('kpi') ? 'has-error' : '' }}">
                                <label for="">Phần trăm sản phẩm</label>
                                <input type="text" class="form-control" name="kpi" placeholder="VD: 0.3 ~ 30%" value="{{ old('kpi', $product->kpi) }}">
                                <span class="help-block">{{ $errors->first('kpi') }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-warning"><i class="fa fa-floppy-o" aria-hidden="true"></i> Cập nhật</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script type="text/javascript">
    </script>
@stop

resources/views/admin/products/index.blade.php
@extends('adminlte::page')

@section('title', $title)

@section('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/admin.css') }}">
@stop

@section('content')
    <div class="row">
        <div class="col-md-12" id="backend-blog">
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title">Danh sách sản phẩm</h3>
                    <span class="pull-right">
                        <a href="{{ route('products.create') }}" class="btn btn-success"><i class="fa fa-plus"></i> Thêm mới</a>
                    </span>
                </div>

                <table class="table table-striped table-hover table-bordered">
                    <thead>
                        <tr>
                            <th width="35">#</th>
                            <th width="100">Mã sản phẩm</th>
                            <th width="200">Tên</th>
                            <th>Mô tả</th>
                            <th width="100">Giá</th>
                            <th width="130">Giá trên mỗi trang</th>
                            <th width="50">%</th>
                            <th width="100" class="text-center">Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($products as $key => $product)
                            <tr>
                                <td class="text-center">{{ ++$key }}</td>
                                <td>{{ $product->getTypes()[$product->type] }}</td>
                                <td>{{ $product->name }}</td>
                                <td>{{ $product->description }}</td>
                                <td>{{ $product->default_price }}</td>
                                <td>{{ $product->price_per_page }}</td>
                                <td>{{ $product->kpi }}</td>
                                <td class="text-center">
                                    <a href="{{ route('products.edit', $product->id) }}" class="btn btn-xs" data-toggle="tooltip" title="Sửa">
                                        <i class="fa fa-pencil" aria-hidden="true"></i>
                                    </a>
                                    <a href="#" data-href="{{ route('products.destroy', $product->id) }}" class="btn btn-xs btn-destroy label-cancel" data-toggle="tooltip" title="Xóa">
                                        <i class="fa fa-times" aria-hidden="true"></i>
                                    </a>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="8" class="text-center">Không có dữ liệu !</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
                <div class="box-footer">
                    <div class="pull-right">
                        @if (count($products))
                            {!! $products->appends([Request::all()])->links() !!}
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@section('js')
<script type="text/javascript">
</script>
@stop