routes/admin.php
<?php
Route::resource('categories', 'CategoryController');

Route::resource('blogs', 'BlogController');
Route::get('blogs/{id}/active', 'BlogController@active');
Route::get('blogs/{id}/hot', 'BlogController@hot');
Route::post('blogs/upload', 'BlogController@upload')->name('blogs.upload');

Route::resource('products', 'ProductController');
// Route::resource('pages', 'PageController');
Route::get('orders/search', 'ProductController@search')->name('products.search');
Route::resource('orders', 'OrderController');
Route::get('customers/search', 'CustomerController@search')->name('customers.search');
Route::resource('customers', 'CustomerController');

Route::group(['middleware' => ['role:superadmin']], function() {
	Route::resource('permissions', 'PermissionController', ['except' => ['show', 'create']]);
	Route::resource('roles', 'RoleController', ['except' => ['show', 'create']]);
	Route::resource('accounts', 'UserController');
	Route::get('accounts/active/{id}', 'UserController@active')->name('accounts.active');
	Route::get('accounts/reset-password/{id}', 'UserController@resetPasswordDefault')->name('accounts.reset-password');
});

// Route::get('change-password', 'AdminController@getChangePassword')->name('get-change-password');
// Route::post('change-password', 'AdminController@changePassword')->name('change-password');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Categories\CategoryRepository;

class CategoryController extends Controller
{
    protected $category;

    protected $viewPath = 'admin.categories.';
    protected $title    = 'Danh mục';

    protected $rules = [
        'name' => 'required'
    ];

    protected $messages = [
        'name.required' => 'Tên chuyên mục không được để trống!'
    ];

    public function __construct(CategoryRepository $category)
    {
        $this->category = $category;
    }

    public function index(Request $request)
    {
        return view($this->viewPath . 'index')->with([
            'title'         => $this->title,
            'viewPath'      => $this->viewPath,
            'categories'    => $this->category->getAllCategories(),
            'allcategories' => $this->category->recursiveCategories()
        ]);
    }

    public function store(Request $request)
    {
        try {
            $this->validate($request, $this->rules, $this->messages);
                if ($this->category->store($request->all())) {
                    notify()->flash('Thêm mới ' . $this->title . ' thành công', 'success', ['timer' => 1500]);
                    return redirect()->route('categories.index');
                }else {
                    notify()->flash('Thêm mới ' . $this->title . ' thất bại', 'error', [
                        'timer' => 1500]);
                    return redirect()->back();
            }
        } catch(\Illuminate\Validation\ValidationException $exception) {
            notify()->flash('Vui lòng kiểm tra lại các thông tin cần nhập', 'warning', [
                'timer' => 1500]);
            return redirect()->back()->withErrors($exception->validator->errors())->withInput();
        }
    }

    public function edit($id)
    {
        $category = $this->category->getById($id);

        return view($this->viewPath . 'index')->with([
            'title'         => $this->title,
            'viewPath'      => $this->viewPath,
            'categories'    => $this->category->getAllCategories(),
            'allcategories' => $this->category->recursiveCategories(),
            'category_edit' => $category
        ]);
    }

    public function update($id, Request $request)
    {

        $category = $this->category->getById($id);

        $child = $this->category->recursiveCategories($category->id);
        array_shift($child);

        if(count($child) && $category->parent_id <> $request['parent_id']) {
            notify()->flash('Danh mục hiện tại đang là danh mục cha nên không thể cập nhật được phần danh mục', 'error', [
                'timer' => 1500]);
            return redirect()->back();
        }
        if ($category->id == $request['parent_id']) {
            notify()->flash('Danh mục không hợp lệ', 'error', [
                'timer' => 1500]);
            return redirect()->back();
        }
        try {
            $this->validate($request, $this->rules, $this->messages);
                if ($this->category->update($category, $request->all())) {
                    notify()->flash('Cập nhật ' . $this->title . ' thành công', 'success', [
                        'timer' => 1500]);
                    return redirect()->route('categories.index');
                }else {
                    notify()->flash('Cập nhât ' . $this->title . ' thất bại', 'error', [
                        'timer' => 1500]);
                    return redirect()->back();
            }
        } catch(\Illuminate\Validation\ValidationException $exception) {
            notify()->flash('Vui lòng kiểm tra lại các thông tin cần nhập', 'warning', [
                'timer' => 1500]);
            return redirect()->back()->withErrors($exception->validator->errors())->withInput();
        }
    }

    public function destroy($id)
    {
        $category = $this->category->getById($id);

        $id_delete = array_keys($this->category->recursiveCategories($category->id));
        array_shift($id_delete);
        array_push($id_delete, $category->id);

        try {
            if ($this->category->deleteRecursiveCategories($id_delete)) {
                notify()->flash('Xóa ' . $this->title . ' thành công', 'success', [
                    'timer' => 1500]);
                return response()->json([
                    'code'    => 1,
                    'message' => 'Xóa thành công'
                ]);
            }else {
                notify()->flash('Xóa ' . $this->title . ' thất bại', 'error', [
                    'timer' => 1500]);
                return response()->json([
                    'code'    => 0,
                    'message' => 'Xóa thất bại'
                ]);
            }
        } catch(\Illuminate\Validation\ValidationException $exception) {
            notify()->flash('Có lỗi trong quá trình xóa dữ liệu', 'warning', [
                'timer' => 1500]);
            return redirect()->back()->withErrors($exception->validator->errors())->withInput();
        }
    }
}

resources/views/admin/categories/index.blade.php
@extends('adminlte::page')

@section('css')
    <link rel="stylesheet" type="text/css" href="{{ secure_asset('css/admin.css') }}">
    <style type="text/css" media="screen">
        .list-nullstyled {
            list-style: none;
        }
        .tree, .tree ul {
            margin:0;
            padding:0;
            list-style:none;
        }
        .tree ul {
            margin-left:1em;
            position:relative;
        }
        .tree ul ul {
            margin-left:.5em;
        }
        .tree ul:before {
            content:"";
            display:block;
            width:0;
            position:absolute;
            top:0;
            bottom:0;
            left:0;
            border-left:1px solid;
        }
        .tree li {
            margin:0;
            padding:0 1em;
            line-height:2em;
            color:#38B4C9;
            font-weight:700;
            position:relative;margin-bottom;
            cursor: pointer;
        }
        .tree ul li:before {
            content:"";
            display:block;
            width:10px;
            height:0;
            border-top:1px solid;
            margin-top:-1px;
            position:absolute;
            top:1em;
            left:0;
        }
        .tree ul li:last-child:before {
            background:#fff;
            height:auto;
            top:1em;
            bottom:0;
        }
/*        .tree li .bbc_tree__title {
            display: inline-block;
            width: 95%;
            float: right;
            cursor: pointer;
        }*/
        .indicator {
            margin-right:5px;
        }
        .tree li a {
            text-decoration: none;
            color:#38B4C9;
        }
        .tree li button, .tree li button:active, .tree li button:focus {
            text-decoration: none;
            /*color:#38B4C9;*/
            border:none;
            background:transparent;
            margin:0px 0px 0px 0px;
            padding:0px 0px 0px 0px;
            outline: 0;
            margin-right: 5px;
        }
        .box-body .btn-cancel {
            margin-left: 10px;
        }
    </style>
@stop

@section('title', $title)

@section('content_header')
@stop

@section('content')
    <div class="row">
        <div class="col-md-6 col-sm-12 col-xs-12">
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title">Danh sách chuyên mục</h3>
                </div>

                <div class="box-body">
                    <ul id="bbc-tree--categories" class="list-nullstyled">
                        @foreach($categories as $category)
                            <li>
                                <span class="bbc_tree__title">
                                    {{ $category->name }}
                                </span>
                                <button type="button" data-href='{{ route('categories.destroy', $category->id) }}'" class="btn btn-box-tool pull-right btn-detroy label-cancel" data-toggle="tooltip" title="" data-original-title="Xóa">
                                    <i class="fa fa-times"></i>
                                </button>
                                <button type="button" onclick="location.href='{{ route('categories.edit', $category->id) }}'" class="btn btn-box-tool pull-right label-accept" data-toggle="tooltip" title="" data-original-title="Sửa">
                                    <i class="fa fa-pencil"></i>
                                </button>

                                @if(count($category->childs))
                                    @include($viewPath . 'tree', ['childs' => $category->childs])
                                @endif
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>

        </div>

        <div class="col-md-6 col-sm-12 col-xs-12">
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ isset($category_edit) ? 'Cập nhật' : 'Thêm mới' }} chuyên mục</h3>
                </div>
                <div class="box-body">
                    <form action="{{ isset($category_edit) ? route('categories.update', $category_edit->id) : route('categories.store')}}" method="POST" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        @if (isset($category_edit))
                            {{ method_field('PUT') }}
                        @endif
                        <div class="form-group {{ $errors->first('name') ? 'has-error' : ''}}">
                          <label class="control-label" for="title">Tên chuyên mục  <b style="color: red">*</b></label>
                          <input type="text" class="form-control" name="name" id="name" placeholder="Nhập tên chuyên mục" value="{{ old('title', isset($category_edit) ? $category_edit->name : '')  }}">
                          <span class="help-block">{{ $errors->first('name') }}</span>
                        </div>

                        <div class="form-group {{ $errors->first('parent_id') ? 'has-error' : '' }}">
                          <label>Chuyên mục</label>
                          <select name="parent_id" class="form-control">
                            @foreach($allcategories as $key => $category1)
                                <option value="{{ $key }}" {{ isset($category_edit) ? ($key == $category_edit->parent_id ? 'selected' : '') : ''}} >{{ $category1 }}</option>
                            @endforeach
                          </select>
                          <span class="help-block">{{ $errors->first('parent_id') }}</span>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-{{ isset($category_edit) ? 'warning' : 'success' }}">{{ isset($category_edit) ? 'Cập nhật' : 'Thêm mới' }}</button>
                            @if (isset($category_edit))
                                <a href="{{ route('categories.index') }}" class="btn btn-default btn-cancel">Hủy</a>
                            @endif
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script type="text/javascript" charset="utf-8">
        $.fn.extend({
            treed: function (o) {

              var openedClass = 'glyphicon-minus-sign';
              var closedClass = 'glyphicon-plus-sign';

              if (typeof o != 'undefined'){
                if (typeof o.openedClass != 'undefined'){
                    openedClass = o.openedClass;
                }
                if (typeof o.closedClass != 'undefined'){
                    closedClass = o.closedClass;
                }
              };

                //initialize each of the top levels
                var tree = $(this);
                tree.addClass("tree");
                tree.find('li').has("ul").each(function () {
                    var branch = $(this); //li with children ul
                    branch.prepend("<i class='indicator glyphicon " + closedClass + "'></i>");
                    branch.addClass('branch');
                    branch.on('click', function (e) {
                        if (this == e.target) {
                            var icon = $(this).children('i:first');
                            icon.toggleClass(openedClass + " " + closedClass);
                            $(this).children().children().toggle();
                        }
                    })
                    branch.children().children().toggle();
                });
                //fire event from the dynamically added icon
              tree.find('.branch .indicator').each(function(){
                $(this).on('click', function () {
                    $(this).closest('li').click();
                });
              });
                //fire event to open branch if the li contains an anchor instead of text
                tree.find('.branch > a').each(function () {
                    $(this).on('click', function (e) {
                        $(this).closest('li').click();
                        e.preventDefault();
                    });
                });
                //fire event to open branch if the li contains a button instead of text
                tree.find('.branch > button').each(function () {
                    $(this).on('click', function (e) {
                        $(this).closest('li').click();
                        e.preventDefault();
                    });
                });
            }
        });

        //Initialization of treeviews
        //
        $('#bbc-tree--categories').treed();
    </script>
@stop

resources/views/admin/categories/tree.blade.php
<ul class="list-nullstyled">
    @foreach($childs as $child)
        <li>
            <span class="bbc_tree__title">
                {{ $child->name }}
            </span>
            <button type="button" class="btn btn-box-tool pull-right delete-btn" data-href='{{ route('categories.destroy', $child->id) }}'" data-toggle="tooltip" title="" data-original-title="Xóa">
                <i class="fa fa-times"></i>
            </button>
            <button type="button" class="btn btn-box-tool pull-right" onclick="location.href='{{ route('categories.edit', $child->id) }}'" data-toggle="tooltip" title="" data-original-title="Sửa">
                <i class="fa fa-pencil"></i>
            </button>
            @if(count($child->childs))
                @include($viewPath . 'tree', ['childs' => $child->childs])
            @endif
        </li>
    @endforeach
</ul>